
help:
	@echo "show Makefile usage"
	@echo
	@echo "make run    run webserver with morbo"
	@echo "make hyp    run webserver with hypnoatede"
	@echo

run:
	NNSBBS_CONF=net-kaigi morbo script/nns_bbs

hyp:
	NNSBBS_CONF=net-kaigi hypnotoad script/nns_bbs
